services:
  db:
    image: postgres:latest
    container_name: postgres1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_name1
    ports:
      - "5431:5432"
    volumes:
      - postgres1-data:/var/lib/postgresql/data
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
volumes:
  postgres1-data: